FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/server ./cmd/main.go


FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=build /bin/server /app/server
COPY --from=build /app /app
EXPOSE 8080
ENTRYPOINT ["/app/server"]